title: SalesTim URL Shortener
description: âœ‚ï¸ğŸ”— This is a simple repository for making URL Shorteners with Jekyll and GitHub Pages.
logo: /assets/img/color.png
show_downloads: false
google_analytics: UA-5688830-17
theme: jekyll-theme-minimal

permalink: /:slug/

plugins:
  - jekyll-redirect-from
